### ISSUE TITLE
Xiaomi Redmi Note 7 hata bildirimi.

### ISSUE THREAD

**Issue by necmi** [tolgaozuygur/gardiyan#2]
Xiaomi Redmi Note 7 model cihazda aşağıdaki hatayı vermekte ve hiç açılmamakta uygulama. 

```
java.lang.UnsatisfiedLinkError: No implementation found for void com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated() (tried Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated and Java_com_adobe_air_AIRWindowSurfaceView_nativeSurfaceCreated__)
 at com.adobe.air.AIRWindowSurfaceView.nativeSurfaceCreated(Native Method)
 at com.adobe.air.AIRWindowSurfaceView.surfaceCreated(AIRWindowSurfaceView.java:721)
 at android.view.SurfaceView.updateSurface(SurfaceView.java:675)
 at android.view.SurfaceView$2.onPreDraw(SurfaceView.java:143)
 at android.view.ViewTreeObserver.dispatchOnPreDraw(ViewTreeObserver.java:977)
 at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2522)
 at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1505)
 at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7354)
 at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1092)
 at android.view.Choreographer.doCallbacks(Choreographer.java:888)
 at android.view.Choreographer.doFrame(Choreographer.java:819)
 at android.view.Choreographer$FrameHandler.handleMessage(Choreographer.java:991)
 at android.os.Handler.dispatchMessage(Handler.java:106)
 at android.os.Looper.loop(Looper.java:201)
 at android.app.ActivityThread.main(ActivityThread.java:6810)
 at java.lang.reflect.Method.invoke(Native Method)
 at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:547)
 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:873)
```

**Comment by tolgaozuygur** [comment]
Android 9 ise bir problem mevcut, cozmeye calisiyorum

**Comment by necmi** [comment]
Evet android 9 kullanılıyor.

**Comment by tolgaozuygur** [comment]
Sorun cozulmustur
